### ISSUE TITLE
cron task crash

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-portal-server#4]
Mar 26 11:54:00 alldev node: /home/gawatidevserver/portal/filtercache.js:262
Mar 26 11:54:00 alldev node: if (filterValue[KW].length <= KW_THRESHOLD) {
Mar 26 11:54:00 alldev node: ^
Mar 26 11:54:00 alldev node: TypeError: Cannot read property 'length' of undefined
Mar 26 11:54:00 alldev node: at remapKeyWords (/home/gawatidevserver/portal/filtercache.js:262:25)
Mar 26 11:54:00 alldev node: at smartFilterByName (/home/gawatidevserver/portal/filtercache.js:250:18)
Mar 26 11:54:00 alldev node: at Array.map (<anonymous>)
Mar 26 11:54:00 alldev node: at processRouteSmartFilterCache (/home/gawatidevserver/portal/filtercache.js:222:38)
Mar 26 11:54:00 alldev node: at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Mar 26 11:54:00 alldev systemd: gawatidevserver_cron.service: main process exited, code=exited, status=1/FAILURE

**Comment by kohsah** [comment]
@ccsmart Can you attach the full log ?  Seems to happen after its run for a while .

**Comment by ccsmart** [comment]
these two lines in front can probably be attributed to the same process:
Mar 26 11:54:00 alldev node: responseFetchRecent
Mar 26 11:54:00 alldev node: success: created cache portal-cache/recent-docs.json

**Comment by ccsmart** [comment]
there is another instance before, essentially the same, but then, just noticed some smaller differences:
Mar 26 11:54:00 alldev node: /home/gawatidevserver/portal/filtercache.js:262
Mar 26 11:54:00 alldev node: if (filterValue[KW].length <= KW_THRESHOLD) {
Mar 26 11:54:00 alldev node: ^
Mar 26 11:54:00 alldev node: TypeError: Cannot read property 'length' of undefined
Mar 26 11:54:00 alldev node: at remapKeyWords (/home/gawatidevserver/portal/filtercache.js:262:25)
Mar 26 11:54:00 alldev node: at smartFilterByName (/home/gawatidevserver/portal/filtercache.js:250:18)
Mar 26 11:54:00 alldev node: at Array.map (<anonymous>)
Mar 26 11:54:00 alldev node: at processRouteSmartFilterCache (/home/gawatidevserver/portal/filtercache.js:222:38)
Mar 26 11:54:00 alldev node: at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Mar 26 11:54:00 alldev systemd: gawatidevserver_cron.service: main process exited, code=exited, status=1/FAILURE

**Comment by ccsmart** [comment]
funny. i see now, the difference appears to be github cutting some things out.
please see attached original
[Mar 26 11_54_00 alldev node_ _home_gawatidevserver_portal_filtercache.js_262.txt](https://github.com/gawati/gawati-portal-server/files/1847717/Mar.26.11_54_00.alldev.node_._home_gawatidevserver_portal_filtercache.js_262.txt)

**Comment by kohsah** [comment]
Fixed in https://github.com/gawati/gawati-portal-server/commit/674e7e3d64cf532720298d072e06ef71fb567fa7

There was an incorrect file existence check, which was likely the culprit : https://github.com/gawati/gawati-portal-server/commit/674e7e3d64cf532720298d072e06ef71fb567fa7#diff-d4d86a6f43630eea12f11f874d2e8e78L177

**Comment by kohsah** [comment]
@ccsmart Any recurring manifestation of this problem ?

**Comment by ccsmart** [comment]
Apr  2 08:54:14 alldev journal: Suppressed 285330 messages from /system.slice/gawatiserver_server.service
Apr  2 08:54:44 alldev journal: Suppressed 308622 messages from /system.slice/gawatiserver_server.service
Apr  2 08:55:14 alldev journal: Suppressed 299819 messages from /system.slice/gawatiserver_server.service
Apr  2 08:55:44 alldev journal: Suppressed 303355 messages from /system.slice/gawatiserver_server.service

…

Apr  3 09:00:08 alldev journal: Suppressed 536187 messages from /system.slice/gawatiserver_server.service
Apr  3 09:00:38 alldev journal: Suppressed 497716 messages from /system.slice/gawatiserver_server.service
Apr  3 09:01:08 alldev journal: Suppressed 529831 messages from /system.slice/gawatiserver_server.service
Apr  3 09:01:38 alldev journal: Suppressed 528485 messages from /system.slice/gawatiserver_server.service

**Comment by kohsah** [comment]
@ccsmart are those error messages ? there is also a significant amount of info logging by the service which are not errors but informational or warning messages.

**Comment by ccsmart** [comment]
Actually that one made it into the wrong isse. Above suppression messages this is for #5  . Lets wait for #5 fix as at the moment, its hard to find the needle in the haystack of #5 while also not being sure its at all recorded due to suppression due to that one.

**Comment by ccsmart** [comment]
This one just hit again, with updated line numbers:

Apr  9 13:04:44 alldev systemd: Started Gawati API server.
Apr  9 13:04:44 alldev systemd: Starting Gawati API server...
Apr  9 13:05:00 alldev node: /home/gawatidevserver/portal/filtercache.js:248
Apr  9 13:05:00 alldev node: if (filterValue[KW].length <= KW_THRESHOLD) {
Apr  9 13:05:00 alldev node: ^
Apr  9 13:05:00 alldev node: TypeError: Cannot read property 'length' of undefined
Apr  9 13:05:00 alldev node: at remapKeyWords (/home/gawatidevserver/portal/filtercache.js:248:25)
Apr  9 13:05:00 alldev node: at smartFilterByName (/home/gawatidevserver/portal/filtercache.js:236:18)
Apr  9 13:05:00 alldev node: at Array.map (<anonymous>)
Apr  9 13:05:00 alldev node: at processRouteSmartFilterCache (/home/gawatidevserver/portal/filtercache.js:208:38)
Apr  9 13:05:00 alldev node: at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Apr  9 13:05:00 alldev systemd: gawatidevserver_cron.service: main process exited, code=exited, status=1/FAILURE
Apr  9 13:05:00 alldev systemd: Unit gawatidevserver_cron.service entered failed state.
Apr  9 13:05:00 alldev systemd: gawatidevserver_cron.service failed.

**Comment by kohsah** [comment]
@ccsmart  OK ...another fix attempt in 3d1797a4059cb4cd77144790b21f8f2ab27dd86c

**Comment by ccsmart** [comment]
Still unfortunately...

Apr 17 11:01:00 alldev node: /home/gawatidevserver/portal/filtercache.js:259
Apr 17 11:01:00 alldev node: if (filterValue[KW].length <= KW_THRESHOLD) {
Apr 17 11:01:00 alldev node: ^
Apr 17 11:01:00 alldev node: TypeError: Cannot read property 'length' of undefined
Apr 17 11:01:00 alldev node: at remapKeyWords (/home/gawatidevserver/portal/filtercache.js:259:29)
Apr 17 11:01:00 alldev node: at smartFilterByName (/home/gawatidevserver/portal/filtercache.js:248:16)
Apr 17 11:01:00 alldev node: at Array.map (<anonymous>)
Apr 17 11:01:00 alldev node: at processRouteSmartFilterCache (/home/gawatidevserver/portal/filtercache.js:220:40)
Apr 17 11:01:00 alldev node: at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Apr 17 11:01:00 alldev node: success: created smart filter cache

**Comment by kohsah** [comment]
@ccsmart hopefully this https://github.com/gawati/gawati-portal-server/commit/be0e86786146e284dfdac42209d27ebe4fdc2263 should fix the problem

**Comment by kohsah** [comment]
@ccsmart is this still occuring ?

**Comment by ccsmart** [comment]
seems not occuring, would open new one if needed
